-- MySQL Script generated by MySQL Workbench
-- mar 30 oct 2018 16:15:45 -04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema eva
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema eva
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eva` DEFAULT CHARACTER SET latin1 ;
USE `eva` ;

-- -----------------------------------------------------
-- Table `eva`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eva`.`user` ;

CREATE TABLE IF NOT EXISTS `eva`.`user` (
  `user_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eva`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eva`.`role` ;

CREATE TABLE IF NOT EXISTS `eva`.`role` (
  `role_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eva`.`user_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eva`.`user_role` ;

CREATE TABLE IF NOT EXISTS `eva`.`user_role` (
  `user_id` INT(11) UNSIGNED NOT NULL,
  `role_id` INT(11) UNSIGNED NOT NULL,
  INDEX `fk_user_role_user_idx` (`user_id` ASC),
  INDEX `fk_user_role_role1_idx` (`role_id` ASC),
  PRIMARY KEY (`user_id`, `role_id`),
  CONSTRAINT `fk_user_role_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `eva`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_role_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `eva`.`role` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eva`.`class`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eva`.`class` ;

CREATE TABLE IF NOT EXISTS `eva`.`class` (
  `class_id` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`class_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eva`.`user_has_class`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eva`.`user_has_class` ;

CREATE TABLE IF NOT EXISTS `eva`.`user_has_class` (
  `user_id` INT(11) UNSIGNED NOT NULL,
  `class_id` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`user_id`, `class_id`),
  INDEX `fk_user_has_class_class1_idx` (`class_id` ASC),
  INDEX `fk_user_has_class_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_has_class_user1`REFERENCES
    FOREIGN KEY (`user_id`)
    REFERENCES `eva`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_class_class1`
    FOREIGN KEY (`class_id`)
    REFERENCES `eva`.`class` (`class_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
