-- MySQL Script generated by MySQL Workbench
-- mar 13 nov 2018 08:44:58 -04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema eva
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema eva
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eva` DEFAULT CHARACTER SET latin1 ;
USE `eva` ;

-- -----------------------------------------------------
-- Table `eva`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eva`.`user` ;

CREATE TABLE IF NOT EXISTS `eva`.`user` (
  `user_id` INT(11) UNSIGNED NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `created` DATETIME NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eva`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eva`.`role` ;

CREATE TABLE IF NOT EXISTS `eva`.`role` (
  `role_id` INT(11) UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eva`.`user_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eva`.`user_role` ;

CREATE TABLE IF NOT EXISTS `eva`.`user_role` (
  `user_id` INT(11) UNSIGNED NOT NULL,
  `role_id` INT(11) UNSIGNED NOT NULL,
  INDEX `fk_user_role_user_idx` (`user_id` ASC),
  INDEX `fk_user_role_role1_idx` (`role_id` ASC),
  PRIMARY KEY (`user_id`, `role_id`),
  CONSTRAINT `fk_user_role_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `eva`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_role_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `eva`.`role` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eva`.`class`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eva`.`class` ;

CREATE TABLE IF NOT EXISTS `eva`.`class` (
  `class_id` INT(11) UNSIGNED NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `class_code` VARCHAR(45) NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`class_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eva`.`user_has_class`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eva`.`user_has_class` ;

CREATE TABLE IF NOT EXISTS `eva`.`user_has_class` (
  `user_id` INT(11) UNSIGNED NOT NULL,
  `class_id` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`user_id`, `class_id`),
  INDEX `fk_user_has_class_class1_idx` (`class_id` ASC),
  INDEX `fk_user_has_class_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_has_class_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `eva`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_class_class1`
    FOREIGN KEY (`class_id`)
    REFERENCES `eva`.`class` (`class_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eva`.`test`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eva`.`test` ;

CREATE TABLE IF NOT EXISTS `eva`.`test` (
  `test_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `class_id` INT(11) UNSIGNED NOT NULL,
  `start` DATETIME NOT NULL,
  `end` DATETIME NOT NULL,
  `possible_score` DECIMAL NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`test_id`),
  INDEX `fk_test_class1_idx` (`class_id` ASC),
  CONSTRAINT `fk_test_class1`
    FOREIGN KEY (`class_id`)
    REFERENCES `eva`.`class` (`class_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eva`.`question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eva`.`question` ;

CREATE TABLE IF NOT EXISTS `eva`.`question` (
  `question_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(255) NOT NULL,
  `type` ENUM('OPEN', 'BOOL', 'INT', 'DECIMAL', 'SIMPLE', 'MULTIPLE') NOT NULL,
  `percentage` DECIMAL(10,2) NULL,
  `grade` DECIMAL NULL,
  PRIMARY KEY (`question_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eva`.`answer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eva`.`answer` ;

CREATE TABLE IF NOT EXISTS `eva`.`answer` (
  `answer_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `question_id` INT(11) UNSIGNED NOT NULL,
  `user_id` INT(11) UNSIGNED NOT NULL,
  `value` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`answer_id`),
  INDEX `fk_answer_question1_idx` (`question_id` ASC),
  INDEX `fk_answer_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_answer_question1`
    FOREIGN KEY (`question_id`)
    REFERENCES `eva`.`question` (`question_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_answer_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `eva`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eva`.`test_has_question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eva`.`test_has_question` ;

CREATE TABLE IF NOT EXISTS `eva`.`test_has_question` (
  `test_id` INT(11) UNSIGNED NOT NULL,
  `question_id` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`test_id`, `question_id`),
  INDEX `fk_test_has_question_question1_idx` (`question_id` ASC),
  INDEX `fk_test_has_question_test1_idx` (`test_id` ASC),
  CONSTRAINT `fk_test_has_question_test1`
    FOREIGN KEY (`test_id`)
    REFERENCES `eva`.`test` (`test_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_test_has_question_question1`
    FOREIGN KEY (`question_id`)
    REFERENCES `eva`.`question` (`question_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eva`.`assignment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eva`.`assignment` ;

CREATE TABLE IF NOT EXISTS `eva`.`assignment` (
  `assignment_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `class_id` INT(11) UNSIGNED NOT NULL,
  `description` VARCHAR(255) NULL,
  `start` DATETIME NOT NULL,
  `end` DATETIME NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`assignment_id`),
  INDEX `fk_assingment_class1_idx` (`class_id` ASC),
  CONSTRAINT `fk_assingment_class1`
    FOREIGN KEY (`class_id`)
    REFERENCES `eva`.`class` (`class_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eva`.`file`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eva`.`file` ;

CREATE TABLE IF NOT EXISTS `eva`.`file` (
  `file_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `path` VARCHAR(255) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `class_id` INT(11) UNSIGNED NULL,
  `assignment_id` INT UNSIGNED NULL,
  PRIMARY KEY (`file_id`),
  INDEX `fk_file_class1_idx` (`class_id` ASC),
  INDEX `fk_file_assingment1_idx` (`assignment_id` ASC),
  CONSTRAINT `fk_file_class1`
    FOREIGN KEY (`class_id`)
    REFERENCES `eva`.`class` (`class_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_file_assingment1`
    FOREIGN KEY (`assignment_id`)
    REFERENCES `eva`.`assignment` (`assignment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eva`.`user_assignment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eva`.`user_assignment` ;

CREATE TABLE IF NOT EXISTS `eva`.`user_assignment` (
  `user_assignment_id` INT(11) UNSIGNED NOT NULL,
  `file_id` INT UNSIGNED NOT NULL,
  `user_id` INT(11) UNSIGNED NOT NULL,
  `assingment_id` INT UNSIGNED NOT NULL,
  `turn_in_date` DATETIME NOT NULL,
  PRIMARY KEY (`user_assignment_id`),
  INDEX `fk_user_assignment_file1_idx` (`file_id` ASC),
  INDEX `fk_user_assignment_user1_idx` (`user_id` ASC),
  INDEX `fk_user_assignment_assingment1_idx` (`assingment_id` ASC),
  CONSTRAINT `fk_user_assignment_file1`
    FOREIGN KEY (`file_id`)
    REFERENCES `eva`.`file` (`file_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_assignment_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `eva`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_assignment_assingment1`
    FOREIGN KEY (`assingment_id`)
    REFERENCES `eva`.`assignment` (`assignment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eva`.`real_answer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eva`.`real_answer` ;

CREATE TABLE IF NOT EXISTS `eva`.`real_answer` (
  `real_answer_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `question_id` INT(11) UNSIGNED NOT NULL,
  `value` VARCHAR(255) NOT NULL,
  INDEX `fk_real_answer_question1_idx` (`question_id` ASC),
  PRIMARY KEY (`real_answer_id`),
  CONSTRAINT `fk_real_answer_question1`
    FOREIGN KEY (`question_id`)
    REFERENCES `eva`.`question` (`question_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eva`.`score`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eva`.`score` ;

CREATE TABLE IF NOT EXISTS `eva`.`score` (
  `score_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) UNSIGNED NOT NULL,
  `test_id` INT(11) UNSIGNED NULL,
  `assingment_id` INT UNSIGNED NOT NULL,
  `score` DECIMAL(10,2) NULL,
  PRIMARY KEY (`score_id`),
  INDEX `fk_score_user1_idx` (`user_id` ASC),
  INDEX `fk_score_test1_idx` (`test_id` ASC),
  INDEX `fk_score_assingment1_idx` (`assingment_id` ASC),
  CONSTRAINT `fk_score_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `eva`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_score_test1`
    FOREIGN KEY (`test_id`)
    REFERENCES `eva`.`test` (`test_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_score_assingment1`
    FOREIGN KEY (`assingment_id`)
    REFERENCES `eva`.`assignment` (`assignment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
